services:
  role-classification:
    image: ${DOCKER_REG}${DOCKER_REPO}${APP_NAME}:${DOCKER_TAG}
    build:
      context: .
    container_name: role-classification
    environment:
      - TRACKER_API=https://skillab-tracker.csd.auth.gr/api
    ports:
      - '8005:8000'
    labels:
      io.portainer.accesscontrol.teams: skillab-all